{application,datocms_graphql_client,
             [{applications,[kernel,stdlib,elixir,logger,httpoison,
                             eventsource_ex,jason,memoize,neuron]},
              {description,"Helpers for DatoCMS GraphQL access"},
              {modules,['Elixir.DatoCMS.GraphQLClient',
                        'Elixir.DatoCMS.GraphQLClient.Backends.MemoizingClient',
                        'Elixir.DatoCMS.GraphQLClient.Backends.StandardClient',
                        'Elixir.DatoCMS.GraphQLClient.ImageHelpers',
                        'Elixir.DatoCMS.GraphQLClient.MetaTagHelpers',
                        'Elixir.DatoCMS.GraphQLClient.QueryMonitor',
                        'Elixir.DatoCMS.StructuredText',
                        'Elixir.DatoCMS.StructuredText.CustomRenderersError']},
              {registered,[]},
              {vsn,"0.14.9"}]}.
