{application,neuron,
             [{applications,[kernel,stdlib,elixir,logger,httpoison]},
              {description,"A GraphQL client for elixir."},
              {modules,['Elixir.Neuron','Elixir.Neuron.Config',
                        'Elixir.Neuron.ConfigUtils',
                        'Elixir.Neuron.Connection',
                        'Elixir.Neuron.Connection.Http',
                        'Elixir.Neuron.Fragment',
                        'Elixir.Neuron.JSONParseError',
                        'Elixir.Neuron.MissingFragmentsError',
                        'Elixir.Neuron.Response','Elixir.Neuron.Store']},
              {registered,[]},
              {vsn,"4.1.2"}]}.
